<?php
/**
 * @category   Ziffity
 * @package    Ziffity_Preorder
 * @author     ramesh.rajan@ziffity.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
namespace Ziffity\Preorder\Controller\Index;

use Magento\Framework\Controller\ResultFactory; 
        
class Post extends \Magento\Framework\App\Action\Action
{
    

    public function execute()
    {       
        $resultRedirect = $this->resultFactory->create(ResultFactory::TYPE_REDIRECT);
        $post = $this->getRequest()->getPostValue();
       
            try {
                $model = $this->_objectManager->create('Ziffity\Preorder\Model\Preorder');
                $modelCollection = $model->getCollection();
                $record = $modelCollection->addFieldToFilter('email', $post['email']);
                if(!count($record->getData())){
                    $model->setData($post);
                    $model->save();
                    $this->messageManager->addSuccess(
                        __('Thanks for contacting us with your preorder request. We\'ll respond to you very soon.')
                    );   
                    $resultRedirect->setUrl($this->_redirect->getRefererUrl());
                    return $resultRedirect;                      
                }else{
                    $this->messageManager->addNotice(
                        __('You have already requested for preorder please wait while we\'re reviewing your request.')
                    );  
                    $resultRedirect->setUrl($this->_redirect->getRefererUrl());
                    return $resultRedirect;                       
                }                                         
            } catch (\Exception $e) {
                //echo  $e->getMessage().'Error : We can\'t process your request right now'; exit;               
                $this->messageManager->addError(
                    __($e->getMessage().' We can\'t process your request right now. Sorry, that\'s all we know.')
                );
                $resultRedirect->setUrl($this->_redirect->getRefererUrl());
                return $resultRedirect;
            }
        
    }
        
        
        
   
}
