<?php
/**
 * @category   Ziffity
 * @package    Ziffity_Preorder
 * @author     ramesh.rajan@ziffity.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
namespace Ziffity\Preorder\Helper;

class Data extends \Magento\Framework\App\Helper\AbstractHelper
{
    protected $_request;
    protected $moduleManager;
    protected $scopeConfig;

    const XML_PATH_STATUS = 'preorder/general/enable';
    public function __construct
    (
        \Magento\Framework\App\Request\Http $request,
        \Magento\Framework\Module\Manager $moduleManager,
        \Magento\Framework\App\Config\ScopeConfigInterface $scopeConfig
    ) {
        $this->_request = $request;
        $this->moduleManager = $moduleManager;
        $this->scopeConfig = $scopeConfig;
    }

    public function getTemplate()
    {
        $storeScope = \Magento\Store\Model\ScopeInterface::SCOPE_STORE;
        $status = $this->scopeConfig->getValue(self::XML_PATH_STATUS, $storeScope);
        $writer = new \Zend\Log\Writer\Stream(BP . '/var/log/yyr.log');
        $logger = new \Zend\Log\Logger();
        $logger->addWriter($writer);
        $logger->info($status);
        if ($status == true) {
               $template = 'Ziffity_Preorder::product/list.phtml';
        } else {
            $template = 'Magento_Catalog::product/list.phtml';
        }

        return $template;
    }
} 